version: '2'
services:
  jupyter-local:
    # image: jupyter/all-spark-notebook:spark-3.2.0
    build: .
    ports:
      - 8898:8888
      - 6040:4040
      - 6041:4041
    volumes:
      - ./ssh-keys:/home/jovyan/.ssh 
      - ./notebooks:/home/jovyan/work
      - /c/ddmitry/Sources:/home/jovyan/work/sources
    entrypoint: start-notebook.sh --NotebookApp.token=''
