version: '2'
services:
  jupyter-local:
    # build: .
    image: ddmitry80/all-spark-notebook:spark-3.5.0-20240826
    ports:
      - 8898:8888
      - 6040:4040
      - 6041:4041
    volumes:
      - ./ssh-keys:/home/jovyan/.ssh 
      - ./notebooks:/home/jovyan/work
      - ~/sources:/home/jovyan/work/sources
    entrypoint: start-notebook.sh --NotebookApp.token=''
